package artboard.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File

/** Generates the isolated gallery entry point and browser resources. */
@CacheableTask
abstract class GenerateArtboardHostTask : DefaultTask() {
    @get:Input
    abstract val registryPackage: Property<String>

    @get:Input
    abstract val hostPackage: Property<String>

    @get:Input
    abstract val title: Property<String>

    @get:Input
    abstract val entryScript: Property<String>

    /** Selects which entry point to generate; see [GalleryTarget]. */
    @get:Input
    abstract val mode: Property<GalleryMode>

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val composeResourceRoots: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val output = outputDirectory.get().asFile
        output.deleteRecursively()
        HostGenerator.generate(
            outputDir = output,
            registryPackage = registryPackage.get(),
            hostPackage = hostPackage.get(),
            title = title.get(),
            languageTags = LocaleDiscovery.scanRoots(composeResourceRoots.files),
            entryScript = entryScript.get(),
            mode = mode.get(),
        )
    }
}

/**
 * Writes plugin-owned gallery entry sources into [outputDir].
 *
 * Generated main uses [GeneratedArtboardRegistry] from [registryPackage]
 * and [ArtboardSupportedLocales] from project composeResources.
 */
internal object HostGenerator {

    fun generate(
        outputDir: File,
        registryPackage: String,
        hostPackage: String,
        title: String,
        languageTags: Collection<String>,
        entryScript: String,
        mode: GalleryMode,
    ) {
        val kotlinDir = File(outputDir, "kotlin/${hostPackage.replace('.', '/')}")
        val resourcesDir = File(outputDir, "resources")
        kotlinDir.mkdirs()
        resourcesDir.mkdirs()

        when (mode) {
            GalleryMode.Live -> {
                File(kotlinDir, "ArtboardSupportedLocales.kt").writeText(
                    localesKt(hostPackage = hostPackage, languageTags = languageTags),
                )
                File(kotlinDir, "ArtboardHostMain.kt").writeText(
                    mainKt(
                        hostPackage = hostPackage,
                        registryPackage = registryPackage,
                        title = title,
                    ),
                )
                File(resourcesDir, "index.html").writeText(indexHtml(entryScript, title))
            }

            GalleryMode.Snapshot ->
                File(kotlinDir, "ArtboardSnapshotMain.kt").writeText(
                    snapshotMainKt(
                        hostPackage = hostPackage,
                        registryPackage = registryPackage,
                        title = title,
                        languageTags = languageTags,
                    ),
                )

            GalleryMode.AndroidSnapshot ->
                File(kotlinDir, "ArtboardSnapshotTest.kt").writeText(
                    androidSnapshotTestKt(
                        hostPackage = hostPackage,
                        registryPackage = registryPackage,
                        title = title,
                        languageTags = languageTags,
                    ),
                )
        }
    }

    /** Simple class name of the generated Android renderer. */
    const val ANDROID_SNAPSHOT_TEST_CLASS: String = "ArtboardSnapshotTest"

    /** System property carrying the output directory into the Robolectric JVM. */
    const val ANDROID_OUTPUT_PROPERTY: String = "artboard.snapshot.output"

    /**
     * Headless Android renderer, driven by Robolectric on the JVM.
     *
     * Android has no `ImageComposeScene`, so previews are composed for real and
     * captured through Compose's test API. Sizing and naming come from the shared
     * plan in `artboard-runtime`, so the output is interchangeable with the JVM
     * renderer's.
     */
    private fun androidSnapshotTestKt(
        hostPackage: String,
        registryPackage: String,
        title: String,
        languageTags: Collection<String>,
    ): String {
        val titleLiteral = title.kotlinLiteralContents()
        val d = "$"
        val tagLiterals = languageTags.joinToString(", ") { "\"${it.replace("\"", "")}\"" }
        return """
            |// Generated by Artboard Gradle plugin — do not edit.
            |package $hostPackage
            |
            |import androidx.compose.foundation.layout.Box
            |import androidx.compose.foundation.layout.requiredSize
            |import androidx.compose.ui.Modifier
            |import androidx.compose.ui.unit.dp
            |import com.github.takahirom.roborazzi.captureRoboImage
            |import artboard.host.PreviewFrameEnvironment
            |import artboard.snapshot.SNAPSHOT_IMAGES_DIRECTORY
            |import artboard.snapshot.SNAPSHOT_MANIFEST_FILE_NAME
            |import artboard.snapshot.SnapshotFailure
            |import artboard.snapshot.SnapshotLocale
            |import artboard.snapshot.SnapshotManifestFrame
            |import artboard.snapshot.SnapshotRenderSpec
            |import artboard.snapshot.SnapshotTheme
            |import artboard.snapshot.buildSnapshotManifest
            |import artboard.snapshot.snapshotImagePath
            |import artboard.snapshot.snapshotRenderSpecs
            |import artboard.snapshot.withSnapshotLocale
            |import $registryPackage.GeneratedArtboardRegistry
            |import org.junit.Test
            |import org.junit.runner.RunWith
            |import org.robolectric.RobolectricTestRunner
            |import org.robolectric.annotation.Config
            |import org.robolectric.annotation.GraphicsMode
            |import java.io.File
            |
            |/**
            | * Plugin-generated Android snapshot renderer.
            | *
            | *   ./gradlew artboardSnapshot
            | */
            |@RunWith(RobolectricTestRunner::class)
            |@GraphicsMode(GraphicsMode.Mode.NATIVE)
            |@Config(qualifiers = "w2000dp-h2000dp-xhdpi")
            |class $ANDROID_SNAPSHOT_TEST_CLASS {
            |
            |    @Test
            |    fun renderArtboardSnapshots() {
            |        val outputDirectory = File(
            |            requireNotNull(System.getProperty("$ANDROID_OUTPUT_PROPERTY")) {
            |                "Artboard snapshot output directory was not provided"
            |            },
            |        )
            |        val imagesDirectory = File(outputDirectory, SNAPSHOT_IMAGES_DIRECTORY)
            |        imagesDirectory.deleteRecursively()
            |        imagesDirectory.mkdirs()
            |
            |        val locales = SnapshotLocale.axisOf(listOf($tagLiterals))
            |        val failures = mutableListOf<SnapshotFailure>()
            |        val entries = mutableListOf<SnapshotManifestFrame>()
            |        var imageCount = 0
            |
            |        for (spec in snapshotRenderSpecs(GeneratedArtboardRegistry.frames)) {
            |            val images = linkedMapOf<String, Map<String, String>>()
            |            for (locale in locales) {
            |                val themed = linkedMapOf<String, String>()
            |                for (theme in SnapshotTheme.entries) {
            |                    val relativePath = snapshotImagePath(spec.slug, locale.id, theme.id)
            |                    try {
            |                        render(spec, theme, locale, File(outputDirectory, relativePath))
            |                        themed[theme.id] = relativePath
            |                        imageCount++
            |                    } catch (error: Throwable) {
            |                        failures += SnapshotFailure(
            |                            frameId = spec.frame.id,
            |                            locale = locale.id,
            |                            theme = theme.id,
            |                            reason = "${d}{error::class.java.simpleName}: ${d}{error.message}".take(400),
            |                        )
            |                    }
            |                }
            |                if (themed.isNotEmpty()) images[locale.id] = themed
            |            }
            |            entries += SnapshotManifestFrame(
            |                frame = spec.frame,
            |                widthDp = spec.size.widthDp,
            |                heightDp = spec.size.heightDp,
            |                images = images,
            |            )
            |        }
            |
            |        File(outputDirectory, SNAPSHOT_MANIFEST_FILE_NAME).writeText(
            |            buildSnapshotManifest(
            |                title = "$titleLiteral",
            |                scale = SCALE,
            |                locales = locales,
            |                frames = entries,
            |                failures = failures,
            |            ),
            |        )
            |
            |        println("Artboard rendered ${d}imageCount image(s) for ${d}{entries.size} frame(s)")
            |        failures.forEach { failure ->
            |            System.err.println(
            |                "Artboard could not render ${d}{failure.frameId} " +
            |                    "[${d}{failure.theme}]: ${d}{failure.reason}",
            |            )
            |        }
            |        // A run that produced nothing is a failed run, not a quiet success.
            |        if (imageCount == 0 && entries.isNotEmpty()) {
            |            throw AssertionError(
            |                "Artboard rendered no images for ${d}{entries.size} frame(s); " +
            |                    "${d}{failures.size} variant(s) failed. First: " +
            |                    "${d}{failures.firstOrNull()?.reason}",
            |            )
            |        }
            |    }
            |
            |    /**
            |     * Captures one variant.
            |     *
            |     * Roborazzi's composable overload builds and disposes its own composition per
            |     * call, so a loop works and Compose's test-host idling — which times out under
            |     * Robolectric — is never involved.
            |     */
            |    private fun render(
            |        spec: SnapshotRenderSpec,
            |        theme: SnapshotTheme,
            |        locale: SnapshotLocale,
            |        target: File,
            |    ) {
            |        target.parentFile?.mkdirs()
            |        // Robolectric's configuration is fixed for the whole test, so the
            |        // resource locale has to be applied around each capture instead.
            |        withSnapshotLocale(locale.tag) {
            |            captureRoboImage(file = target) {
            |                Box(
            |                    Modifier.requiredSize(spec.size.widthDp.dp, spec.size.heightDp.dp),
            |                ) {
            |                    PreviewFrameEnvironment(isDark = theme.isDark, localeTag = locale.tag) {
            |                        spec.frame.content()
            |                    }
            |                }
            |            }
            |        }
            |        check(target.isFile && target.length() > 0L) {
            |            "Roborazzi wrote no image for ${d}{spec.frame.id}"
            |        }
            |    }
            |
            |    private companion object {
            |        /** Matches the xhdpi qualifier above and the JVM renderer's default. */
            |        const val SCALE = 2f
            |    }
            |}
            |
        """.trimMargin()
    }

    /** Simple class name of the generated snapshot entry point. */
    const val SNAPSHOT_MAIN_CLASS: String = "ArtboardSnapshotMainKt"

    /**
     * Headless renderer entry point for snapshot mode.
     *
     * Deliberately tiny: all rendering lives in `artboard-runtime` so it can reuse
     * the board's own sizing and preview-environment rules.
     */
    private fun snapshotMainKt(
        hostPackage: String,
        registryPackage: String,
        title: String,
        languageTags: Collection<String>,
    ): String {
        val titleLiteral = title.kotlinLiteralContents()
        val dollar = "$"
        val tagLiterals = languageTags.joinToString(", ") { "\"${it.replace("\"", "")}\"" }
        return """
            |// Generated by Artboard Gradle plugin — do not edit.
            |package $hostPackage
            |
            |import artboard.snapshot.ArtboardSnapshotRenderer
            |import artboard.snapshot.SnapshotLocale
            |import artboard.snapshot.SnapshotOptions
            |import artboard.snapshot.SNAPSHOT_IMAGE_WARN_THRESHOLD
            |import artboard.snapshot.snapshotImageCount
            |import $registryPackage.GeneratedArtboardRegistry
            |import java.io.File
            |
            |/**
            | * Plugin-generated headless snapshot renderer.
            | *
            | *   ./gradlew artboardSnapshot
            | */
            |fun main(args: Array<String>) {
            |    val outputDirectory = File(
            |        args.firstOrNull() ?: error("Artboard snapshot output directory is required"),
            |    )
            |    val locales = SnapshotLocale.axisOf(listOf($tagLiterals))
            |    val planned = snapshotImageCount(
            |        frames = GeneratedArtboardRegistry.frames.size,
            |        locales = locales.size,
            |        themes = 2,
            |    )
            |    println(
            |        "Artboard rendering ${dollar}planned image(s): " +
            |            "${dollar}{GeneratedArtboardRegistry.frames.size} frame(s) x " +
            |            "${dollar}{locales.size} locale(s) x 2 theme(s)",
            |    )
            |    if (planned > SNAPSHOT_IMAGE_WARN_THRESHOLD) {
            |        System.err.println(
            |            "Artboard warning: ${dollar}planned images exceeds " +
            |                "${dollar}SNAPSHOT_IMAGE_WARN_THRESHOLD. Narrow the locale axis with " +
            |                "artboard { snapshotLocales.set(listOf(...)) } if this is too slow.",
            |        )
            |    }
            |    val result = ArtboardSnapshotRenderer.render(
            |        registry = GeneratedArtboardRegistry,
            |        options = SnapshotOptions(
            |            outputDirectory = outputDirectory,
            |            title = "$titleLiteral",
            |            locales = locales,
            |        ),
            |    )
            |    println(
            |        "Artboard rendered ${dollar}{result.imageCount} image(s) " +
            |            "for ${dollar}{result.frameCount} frame(s)",
            |    )
            |    result.failures.forEach { failure ->
            |        System.err.println(
            |            "Artboard could not render ${dollar}{failure.frameId} " +
            |                "[${dollar}{failure.theme}]: ${dollar}{failure.reason}",
            |        )
            |    }
            |    // A run that produced nothing is a failed run, not a quiet success.
            |    if (result.imageCount == 0 && result.frameCount > 0) {
            |        System.err.println(
            |            "Artboard rendered no images for ${dollar}{result.frameCount} frame(s); " +
            |                "every variant failed.",
            |        )
            |        kotlin.system.exitProcess(1)
            |    }
            |}
            |
        """.trimMargin()
    }

    private fun localesKt(
        hostPackage: String,
        languageTags: Collection<String>,
    ): String {
        val tagLiterals = languageTags.joinToString(", ") { "\"${it.replace("\"", "")}\"" }
        return """
            |// Generated by Artboard Gradle plugin — do not edit.
            |package $hostPackage
            |
            |import artboard.host.ArtboardLocale
            |import artboard.host.artboardLocalesFromResourceTags
            |
            |/**
            | * Locales discovered from this module's `composeResources/values*` folders.
            | * Used by the gallery locale control (System + each resource language).
            | */
            |object ArtboardSupportedLocales {
            |    private val resourceLanguageTags: List<String> = listOf($tagLiterals)
            |
            |    val all: List<ArtboardLocale> =
            |        artboardLocalesFromResourceTags(resourceLanguageTags)
            |}
            |
        """.trimMargin()
    }

    private fun mainKt(
        hostPackage: String,
        registryPackage: String,
        title: String,
    ): String {
        val titleLiteral = title.kotlinLiteralContents()
        return """
            |// Generated by Artboard Gradle plugin — do not edit.
            |@file:OptIn(
            |    androidx.compose.ui.ExperimentalComposeUiApi::class,
            |    kotlin.js.ExperimentalWasmJsInterop::class,
            |)
            |package $hostPackage
            |
            |import androidx.compose.runtime.getValue
            |import androidx.compose.runtime.LaunchedEffect
            |import androidx.compose.runtime.mutableStateOf
            |import androidx.compose.runtime.remember
            |import androidx.compose.runtime.setValue
            |import androidx.compose.ui.window.ComposeViewport
            |import artboard.canvas.ArtboardFocusRequest
            |import artboard.host.ArtboardApp
            |import artboard.registry.CompositeArtboardRegistry
            |import artboard.registry.resolveFrameId
            |import $registryPackage.GeneratedArtboardRegistry
            |import kotlinx.browser.document
            |import kotlinx.browser.window
            |import org.w3c.dom.events.Event
            |
            |/**
            | * Plugin-generated Wasm gallery entry.
            | *
            | *   ./gradlew artboardRun
            | */
            |fun main() {
            |    val body = document.body ?: error("document.body is null")
            |    ComposeViewport(viewportContainer = body) {
            |        val registry = remember {
            |            CompositeArtboardRegistry(GeneratedArtboardRegistry)
            |        }
            |        val initialExternalId = remember { readFrameIdFromHash() }
            |        val initialFrameId = remember(registry) { registry.resolveFrameId(initialExternalId) }
            |        var selectedFrameId by remember { mutableStateOf(initialFrameId) }
            |        var nextFocusToken by remember { mutableStateOf(2L) }
            |        var focusRequest by remember {
            |            mutableStateOf(initialFrameId?.let { ArtboardFocusRequest(it, 1L) })
            |        }
            |
            |        LaunchedEffect(Unit) {
            |            if (initialExternalId != initialFrameId) writeFrameIdToHash(initialFrameId)
            |        }
            |
            |        androidx.compose.runtime.DisposableEffect(registry) {
            |            val listener: (Event) -> Unit = {
            |                val resolved = registry.resolveFrameId(readFrameIdFromHash())
            |                selectedFrameId = resolved
            |                focusRequest = resolved?.let {
            |                    ArtboardFocusRequest(it, nextFocusToken++)
            |                }
            |            }
            |            window.addEventListener("hashchange", listener)
            |            onDispose {
            |                window.removeEventListener("hashchange", listener)
            |            }
            |        }
            |
            |        ArtboardApp(
            |            registry = registry,
            |            title = "$titleLiteral",
            |            selectedFrameId = selectedFrameId,
            |            focusRequest = focusRequest,
            |            onFocusRequestConsumed = { token ->
            |                if (focusRequest?.token == token) focusRequest = null
            |            },
            |            onSelectedFrameIdChange = { id ->
            |                selectedFrameId = id
            |                writeFrameIdToHash(id)
            |            },
            |            // From composeResources/values* (ArtboardSupportedLocales).
            |            supportedLocales = ArtboardSupportedLocales.all,
            |        )
            |    }
            |}
            |
            |private fun readFrameIdFromHash(): String? {
            |    val hash = window.location.hash.removePrefix("#")
            |    if (hash.isBlank()) return null
            |    return when {
            |        hash.startsWith("frame=") -> decodeFrameId(hash.removePrefix("frame="))
            |        hash.contains("=") -> null
            |        else -> decodeFrameId(hash)
            |    }
            |}
            |
            |private fun writeFrameIdToHash(id: String?) {
            |    val next = if (id.isNullOrBlank()) "" else "#frame=${'$'}{encodeFrameId(id)}"
            |    if (window.location.hash != next) {
            |        val base = window.location.pathname + window.location.search
            |        window.history.replaceState(null, "", base + next)
            |    }
            |}
            |
            |private fun encodeFrameId(value: String): String = js("encodeURIComponent(value)")
            |
            |private fun decodeFrameIdUnsafe(value: String): String = js("decodeURIComponent(value)")
            |
            |private fun decodeFrameId(value: String): String? = try {
            |    decodeFrameIdUnsafe(value)
            |} catch (_: Throwable) {
            |    null
            |}
            |
        """.trimMargin()
    }

    private fun indexHtml(scriptName: String, title: String = "Artboard"): String =
        """
        |<!DOCTYPE html>
        |<html lang="en">
        |<head>
        |    <meta charset="UTF-8">
        |    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        |    <title>${title.htmlEscape()}</title>
        |    <link rel="icon" href="$ARTBOARD_FAVICON">
        |    <style>
        |        :root {
        |            --ab-paper: #EFEDE8;
        |            --ab-ink: #262421;
        |            --ab-grid-minor: rgba(38, 36, 33, 0.05);
        |            --ab-grid-major: rgba(38, 36, 33, 0.10);
        |        }
        |        @media (prefers-color-scheme: dark) {
        |            :root {
        |                --ab-paper: #201E1C;
        |                --ab-ink: #E9E6DF;
        |                --ab-grid-minor: rgba(233, 230, 223, 0.045);
        |                --ab-grid-major: rgba(233, 230, 223, 0.09);
        |            }
        |        }
        |        html, body {
        |            margin: 0;
        |            padding: 0;
        |            width: 100%;
        |            height: 100%;
        |            overflow: hidden;
        |            background: var(--ab-paper);
        |        }
        |        /* Graph-paper holding screen shown until the Compose canvas mounts. */
        |        #artboard-loading {
        |            position: fixed;
        |            inset: 0;
        |            z-index: 10;
        |            display: flex;
        |            flex-direction: column;
        |            align-items: center;
        |            justify-content: center;
        |            gap: 10px;
        |            background-color: var(--ab-paper);
        |            background-image:
        |                linear-gradient(var(--ab-grid-major) 1px, transparent 1px),
        |                linear-gradient(90deg, var(--ab-grid-major) 1px, transparent 1px),
        |                linear-gradient(var(--ab-grid-minor) 1px, transparent 1px),
        |                linear-gradient(90deg, var(--ab-grid-minor) 1px, transparent 1px);
        |            background-size: 64px 64px, 64px 64px, 8px 8px, 8px 8px;
        |            opacity: 1;
        |            transition: opacity 240ms ease;
        |        }
        |        #artboard-loading.artboard-loading--done {
        |            opacity: 0;
        |            pointer-events: none;
        |        }
        |        #artboard-loading .artboard-wordmark {
        |            font-family: ui-sans-serif, -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;
        |            font-size: 22px;
        |            font-weight: 600;
        |            letter-spacing: 0.06em;
        |            color: var(--ab-ink);
        |        }
        |        #artboard-loading .artboard-hint {
        |            font-family: ui-sans-serif, -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;
        |            font-size: 12px;
        |            letter-spacing: 0.04em;
        |            color: var(--ab-ink);
        |            opacity: 0.55;
        |        }
        |        @media (prefers-reduced-motion: no-preference) {
        |            #artboard-loading .artboard-wordmark {
        |                animation: artboard-pulse 1.6s ease-in-out infinite;
        |            }
        |            @keyframes artboard-pulse {
        |                0%, 100% { opacity: 1; }
        |                50% { opacity: 0.55; }
        |            }
        |        }
        |    </style>
        |    <!--
        |      Compose Multiplatform web locale override:
        |      https://kotlinlang.org/docs/multiplatform/compose-resource-environment.html
        |    -->
        |    <script>
        |        (function () {
        |            window.addEventListener("error", function (event) {
        |                var error = event.error;
        |                console.error("Artboard uncaught:", error && (error.stack || error.message) || event.message);
        |            });
        |            window.addEventListener("unhandledrejection", function (event) {
        |                var reason = event.reason;
        |                console.error("Artboard rejected:", reason && (reason.stack || reason.message) || reason);
        |            });
        |            var desc = Object.getOwnPropertyDescriptor(Navigator.prototype, "languages");
        |            Object.defineProperty(Navigator.prototype, "languages", {
        |                configurable: true,
        |                enumerable: true,
        |                get: function () {
        |                    var custom = globalThis.__customLocale;
        |                    if (custom) {
        |                        return [String(custom)];
        |                    }
        |                    return desc && desc.get ? desc.get.call(this) : [navigator.language || "en"];
        |                }
        |            });
        |            var langDesc = Object.getOwnPropertyDescriptor(Navigator.prototype, "language");
        |            Object.defineProperty(Navigator.prototype, "language", {
        |                configurable: true,
        |                enumerable: true,
        |                get: function () {
        |                    var custom = globalThis.__customLocale;
        |                    if (custom) {
        |                        return String(custom);
        |                    }
        |                    return langDesc && langDesc.get ? langDesc.get.call(this) : "en";
        |                }
        |            });
        |        })();
        |    </script>
        |</head>
        |<body>
        |<div id="artboard-loading">
        |    <div class="artboard-wordmark">Artboard</div>
        |    <div class="artboard-hint">Loading previews…</div>
        |</div>
        |<script>
        |    // Fade the holding screen out the moment ComposeViewport appends its canvas.
        |    (function () {
        |        var loading = document.getElementById("artboard-loading");
        |        if (!loading) {
        |            return;
        |        }
        |        var dismiss = function () {
        |            loading.classList.add("artboard-loading--done");
        |            var remove = function () {
        |                if (loading.parentNode) {
        |                    loading.parentNode.removeChild(loading);
        |                }
        |            };
        |            loading.addEventListener("transitionend", remove, { once: true });
        |            setTimeout(remove, 400);
        |        };
        |        var observer = new MutationObserver(function (mutations) {
        |            for (var i = 0; i < mutations.length; i++) {
        |                var added = mutations[i].addedNodes;
        |                for (var j = 0; j < added.length; j++) {
        |                    if (added[j].tagName === "CANVAS") {
        |                        observer.disconnect();
        |                        dismiss();
        |                        return;
        |                    }
        |                }
        |            }
        |        });
        |        observer.observe(document.body, { childList: true });
        |    })();
        |</script>
        |<script type="module" src="$scriptName"></script>
        |</body>
        |</html>
        |
        """.trimMargin()
}

private const val ARTBOARD_FAVICON =
    "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E" +
        "%3Crect width='64' height='64' rx='12' fill='%23262421'/%3E" +
        "%3Ctext x='32' y='44' text-anchor='middle' font-family='sans-serif' " +
        "font-size='38' fill='%23EFEDE8'%3EA%3C/text%3E%3C/svg%3E"

private fun String.htmlEscape(): String = buildString {
    for (character in this@htmlEscape) {
        append(
            when (character) {
                '&' -> "&amp;"
                '<' -> "&lt;"
                '>' -> "&gt;"
                '"' -> "&quot;"
                '\'' -> "&#39;"
                else -> character
            },
        )
    }
}

private fun String.kotlinLiteralContents(): String = buildString {
    for (character in this@kotlinLiteralContents) {
        when (character) {
            '\\' -> append("\\\\")
            '"' -> append("\\\"")
            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            '$' -> append("\\$")
            else -> append(character)
        }
    }
}
